VillaWebApp/Controllers/AuthController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Villa_Utility;
using VillaWebApp.Models;
using VillaWebApp.Models.DTO;
using VillaWebApp.Services.IServices;

namespace VillaWebApp.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    [HttpGet]
    public IActionResult Login()
    {
        LoginRequestDTO obj = new();
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginRequestDTO obj)
    {
        APIResponse response = await _authService.LoginAsync<APIResponse>(obj);
        if (response.IsSuccessful)
        {
            LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result)!)!;

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, model.LocalUser!.UserName));
            identity.AddClaim(new Claim(ClaimTypes.Role, model.LocalUser!.Role));
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
            HttpContext.Session.SetString(StaticDetails.SessionToken, model.Token);
            return RedirectToAction("Index", "Home");
        }
        else
        {
            ModelState.AddModelError("CustomError", response.ErrorMessages!.FirstOrDefault()!);
            return View(obj);
        }
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register(RegistrationRequestDTO obj)
    {
        APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
        if (result.IsSuccessful)
        {
            return RedirectToAction("Login");
        }
        return View(obj);
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        HttpContext.Session.SetString(StaticDetails.SessionToken, String.Empty);
        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult AccessDenied()
    {
        return View();
    }
}

VillaWebApp/Controllers/VillaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Villa_Utility;
using VillaWebApp.Models;
using VillaWebApp.Models.DTO;
using VillaWebApp.Services.IServices;

namespace VillaWebApp.Controllers;


public class VillaController : Controller
{
    private readonly IVillaService _villaService;
    private readonly IMapper _mapper;

    public VillaController(IVillaService villaService, IMapper mapper)
    {
        _villaService = villaService;
        _mapper = mapper;
    }
    
    // GET
    public async Task<IActionResult> IndexVilla()
    {
        List<VillaDTO> list = new();

        var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            list = JsonConvert.DeserializeObject<List<VillaDTO>>(response.Result.ToString()!) ?? new();
        }
        
        return View(list);
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdateVilla(int id)
    {
        var response = await _villaService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            VillaDTO? model = JsonConvert.DeserializeObject<VillaDTO>(response.Result.ToString()!);
            return View(_mapper.Map<VillaUpdateDTO>(model));
        }
        
        return NotFound();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response?.Result is not null && response.IsSuccessful)
            {
                TempData["success"] = "Villa updated successfully.";
                return RedirectToAction(nameof(IndexVilla));
            }
        }
        
        TempData["error"] = "Villa update failed.";
        return View(model);
    }
    
    [Authorize(Roles = "Admin")]
    public IActionResult CreateVilla()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response?.Result is not null && response.IsSuccessful)
            {
                TempData["success"] = "Villa created successfully.";
                return RedirectToAction(nameof(IndexVilla));
            }
        }
        
        TempData["error"] = "Villa creation failed.";
        return View(model);
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteVilla(int id)
    {
        var response = await _villaService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            VillaDTO? model = JsonConvert.DeserializeObject<VillaDTO>(response.Result.ToString()!);
            return View(_mapper.Map<VillaDTO>(model));
        }
        
        return NotFound();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteVilla(VillaDTO model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response.IsSuccessful)
            {
                TempData["success"] = "Villa deleted successfully.";
                return RedirectToAction(nameof(IndexVilla));
            }
        }
        
        TempData["error"] = "Villa deletion failed.";
        return View(model);
    }
}

VillaWebApp/Controllers/VillaNumberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Villa_Utility;
using VillaWebApp.Models;
using VillaWebApp.Models.DTO;
using VillaWebApp.Models.ViewModels;
using VillaWebApp.Services.IServices;

namespace VillaWebApp.Controllers;

public class VillaNumberController : Controller
{
    private readonly IVillaNumberService _villaNumberService;
    private readonly IVillaService _villaService;
    private readonly IMapper _mapper;

    public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService, IMapper mapper)
    {
        _villaNumberService = villaNumberService;
        _villaService = villaService;
        _mapper = mapper;
    }
    
    // GET
    public async Task<IActionResult> IndexVillaNumber()
    {
        List<VillaNumberDTO> list = new();

        var response = await _villaNumberService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(response.Result.ToString()!) ?? new();
        }
        
        return View(list);
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdateVillaNumber(int id)
    {
        var response = await _villaNumberService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            VillaNumberUpdateVM vm = new();
            
            VillaNumberDTO? model = JsonConvert.DeserializeObject<VillaNumberDTO>(response.Result.ToString()!);
            vm.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model);
            
            if (response?.Result is not null && response.IsSuccessful)
            {
                vm.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(response.Result.ToString()!)!.Select(u => new SelectListItem()
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
            }

            return View(vm);
        }
        
        return NotFound();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response?.Result is not null && response.IsSuccessful)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
        }
        
        return View(model);
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> CreateVillaNumber()
    {
        var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        VillaNumberCreateVM vm = new();
        
        if (response?.Result is not null && response.IsSuccessful)
        {
            vm.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(response.Result.ToString()!)!.Select(u => new SelectListItem()
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });;
        }

        return View(vm);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response?.Result is not null && response.IsSuccessful)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
        }
        
        return View(model);
    }
    
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteVillaNumber(int id)
    {
        var response = await _villaNumberService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(StaticDetails.SessionToken)!);

        if (response?.Result is not null && response.IsSuccessful)
        {
            VillaNumberDTO? model = JsonConvert.DeserializeObject<VillaNumberDTO>(response.Result.ToString()!);
            return View(_mapper.Map<VillaNumberDTO>(model));
        }
        
        return NotFound();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteVillaNumber(VillaNumberDTO model)
    {
        if (ModelState.IsValid)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNo, HttpContext.Session.GetString(StaticDetails.SessionToken)!);
            if (response.IsSuccessful)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
        }
        
        return View(model);
    }
}

VillaWebApp/Views/Shared/_Layout.cshtml
@using Villa_Utility
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - VillaWebApp</title>
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/> -->
    <link rel="stylesheet" href="~/css/bootswatch_cyborg.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <!-- <link rel="stylesheet" href="~/VillaWebApp.styles.css" asp-append-version="true"/> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
<partial name="_Notification"/>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VillaWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                    </li>
                    @if (HttpContextAccessor.HttpContext?.Session.GetString(StaticDetails.SessionToken) is not null
                         && HttpContextAccessor.HttpContext.Session.GetString(StaticDetails.SessionToken) != String.Empty)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                    }
                                        
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container">
        &copy; 2023 - VillaWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VillaWebApp/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] is not null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000
        })
    </script>
}

@if (TempData["error"] is not null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000
        })
    </script>
}